flow:
  - script: "echo 'hello world'"
    envs:
      FLOW_WORKSPACE: "~/flow-platform/test/id/1/1/3"
      FLOW_VERSION: "1.0.0.0.0"
    steps:
     - name: step1
       allowFailure: false
       script: |
        git clone git@github.com:yunheli/info.git
        export FLOW_GIT_BRANCH=master
        export FLOW_GIT_CHANGELOG=test
        export FLOW_GIT_COMMITER=WILL
        export FLOW_GIT_COMMIT_ID=1234
        export FLOW_GIT_COMPARE_ID=1234....12121111
        echo $FLOW_WORKSPACE
        mkdir -p $FLOW_WORKSPACE
        sleep 2
        echo a
        echo b
        echo c
        echo d
        max=5
        max=10
        for i in `seq 2 $max`
        do
          sleep 1
          echo "$i"
        done
     - name: step2
       allowFailure: true
       script: |
        cd $FLOW_WORKSPACE
        echo a
     - name: step3
       allowFailure: false
       script: |
        #cd $FLOW_WORKSPACE
        #cd info
        #bundle
        #rake test 
        echo a
        max=10
        for i in `seq 2 $max`
        do
          sleep 1
          echo "$i"
        done
     - name: step4
       allowFailure: false
       script: |
        #cd $FLOW_WORKSPACE
        #cd info
        #bundle
        #rake test 
        echo a
        max=10
        for i in `seq 2 $max`
        do
          sleep 1
          echo "$i"
        done
     - name: step5
       allowFailure: false
       script: |
        #cd $FLOW_WORKSPACE
        #cd info
        #bundle
        #rake test 
        echo a
        max=10
        for i in `seq 2 $max`
        do
          sleep 1
          echo "$i"
        done
     - name: step6
       allowFailure: false
       script: |
        #cd $FLOW_WORKSPACE
        #cd info
        #bundle
        #rake test 
        echo a
        max=10
        for i in `seq 2 $max`
        do
          sleep 1
          echo "$i"
        done
      
